version: "3"
services:
  web:
    build:
      context: .
      args:
        NODE_ENV: production
    image: hypercat:1.0
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - PORT=3000
    command: yarn start
